application: lazyhacking
version: 1
runtime: go
api_version: go1

inbound_services:
  - channel_presence

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /js
  static_dir: static/js

- url: /app\.apk
  static_files: static/apks/app.apk
  upload: static/apks/app\.apk

- url: /.*
  script: _go_app
